version: '3.8'

#create a volume for the my sql container.To ensure Data persists after my sql container is stopped
volumes:
  datafiles:

services:
  #DataBase Service
  database:
    image: mysql:5.7
    ports:
      - "3306:3306"
    #Specify where the persisted Data should be stored
    volumes:
      - datafiles:/var/lib/mysql
      - "~/sql-scripts/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    command: ["--log_error_verbosity=2"]
    restart: always
    #Specify Environment Variables for mysql
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      MYSQL_DATABASE: warrendb
  #Api  Service
  api:
    build:
      context: .
      #Use the DockerFile in that Directory
      dockerfile: ContaCorrente.API/Dockerfile
    #This Service Depends on the database service specifed above
    depends_on: 
      - database
    #Map port 8888 in the docker container to port 80 in the Api
    ports:
      - "5000:80"
    command: ["dotnet", "watch", "run"]
    restart: always
    #Specify Environment Variables for the Api Service
    environment: 
      - DBHOST=database
      - DBPORT=3306
      - DBPASSWORD=root
      - ASPNETCORE_ENVIRONMENT=Development
      